{
  "openapi": "3.0.1",
  "info": {
    "title": "API-Hotel",
    "version": "1.0.0"
  },
  "paths": {
    "/api/hotels": {
      "get": {
        "tags": [
          "Hotels"
        ],
        "summary": "Find all hotels.",
        "description": "Returns a list of all hotels.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Hotel"
                  }
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Hotel California",
                    "city": "Los Angeles",
                    "address": "1670 Ocean Avenue"
                  },
                  {
                    "id": 2,
                    "name": "Hotel Transylvania",
                    "city": "Hunedoara",
                    "address": "Pia»õa Iuliu Maniu, no. 11"
                  },
                  {
                    "id": 3,
                    "name": "The Plaza",
                    "city": "New York",
                    "address": "Fifth Avenue at Central Park South"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "message": "Could not find any hotel"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Hotels"
        ],
        "summary": "Add a new hotel.",
        "description": "Creates a new hotel and returns it.",
        "requestBody": {
          "description": "Hotel Object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Hotel"
              },
              "example": {
                "name": "Hotel California",
                "city": "Los Angeles",
                "address": "1670 Ocean Avenue"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Hotel"
                },
                "example": {
                  "id": 1,
                  "name": "Hotel California",
                  "city": "Los Angeles",
                  "address": "1670 Ocean Avenue"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "message": "Missing address, cannot insert"
                }
              }
            }
          }
        }
      }
    },
    "/api/hotels/{id}": {
      "get": {
        "tags": [
          "Hotels"
        ],
        "summary": "Find a hotel by ID.",
        "description": "Returns a hotel.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "hotel ID",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Hotel"
                },
                "example": {
                  "id": 1,
                  "name": "Hotel California",
                  "city": "Los Angeles",
                  "address": "1670 Ocean Avenue"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "message": "Could not find hotel with that id"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Hotels"
        ],
        "summary": "Update an existing hotel by ID.",
        "description": "Updates an existing hotel and returns it.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Hotel ID",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Hotel Object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Hotel"
              },
              "example": {
                "name": "Hotel California",
                "city": "Los Angeles",
                "address": "1670 Ocean Avenue"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Hotel"
                },
                "example": {
                  "id": 1,
                  "name": "Hotel California",
                  "city": "Los Angeles",
                  "address": "1670 Ocean Avenue"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "message": "Hotel doesn't exist, cannot update"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "Hotel": {
        "required": [
          "id",
          "name",
          "city",
          "address"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "minLength": 1,
            "nullable": false
          },
          "name": {
            "minLength": 1,
            "type": "string",
            "nullable": false
          },
          "city": {
            "minLength": 1,
            "type": "string",
            "nullable": false
          },
          "address": {
            "minLength": 1,
            "type": "string",
            "nullable": false
          }
        },
        "additionalProperties": false
      }
    }
  }
}
